### PR TITLE
Switch to using Jenkins Configuration as Code

### PR DESCRIPTION
**Pull request by maratoid**

### CODE REVIEW

**Comment by alika** [comment]
Learned about [Jenkins Configuration as Code Plugin](https://github.com/jenkinsci/configuration-as-code-plugin), reviewed commits, tried to run local go tests, tried to build image locally. JCASK seems like a natural conversion of jenkins system and job configuration to the declarative world of this Kubernetes Jenkins operator. After running dep (~15 mins,  😢), I ran into an issue w/the controller-gen tool:
```
alika@metallic-08:19:39 jenkins-operator (pr/20)$ time make -f build/Makefile test
go run /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd --output-dir /Users/alika/golang/src/github.co
m/samsung-cnct/jenkins-operator/crd
stat /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go: no such file or directory
make: *** [manifests] Error 1
```

Also got a similar error on image build:
```
Step 10/14 : RUN make -f build/Makefile install-dep linux
 ---> Running in e7eee0958291
go get -u github.com/golang/dep/cmd/dep
go get -u github.com/go-bindata/go-bindata/...
go get -u github.com/onsi/ginkgo/ginkgo
go get -u github.com/onsi/gomega/...
go run /go/src/github.com/maratoid/jenkins-operator/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go crd --output-dir /go/src/github.com/maratoid/jenkins-operator/crd
stat /go/src/github.com/maratoid/jenkins-operator/vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go: no such file or directory
build/Makefile:62: recipe for target 'manifests' failed
make: *** [manifests] Error 1
The command '/bin/sh -c make -f build/Makefile install-dep linux' returned a non-zero code: 2
make: *** [docker-build] Error 2
```

After some poking around, seems to related to _controller-tools_ no longer being a direct dependency for dep. Messed around with the `build/Makefile` and installed the tool, but then ran into issues running the `manifests` make target:

```
alika@metallic-09:35:02 jenkins-operator (pr/20)$ time make -f build/Makefile manifests                                                                                         [21/5980]
controller-gen crd --output-dir /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/crd
CRD files generated, files can be found under path /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/crd.
controller-gen rbac --name rbac --output-dir /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/rbac
RBAC manifests generated under '/Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/rbac' directory
output=$(kustomize build build/kustomize/rbac/role); echo "$output" > /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/deployments/helm/jenkins-operator/RBAC/rbac_role.y
aml
Error: rawResources failed to read Resources: Load from path ../../../../rbac/rbac_role.yaml failed: security; file '../../../../rbac/rbac_role.yaml' is not in or below '/Users/alika/go
lang/src/github.com/samsung-cnct/jenkins-operator/build/kustomize/rbac/role'

output=$(kustomize build build/kustomize/rbac/rolebinding); echo "$output" > /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/deployments/helm/jenkins-operator/RBAC/rbac
_role_binding.yaml
Error: rawResources failed to read Resources: Load from path ../../../../rbac/rbac_role_binding.yaml failed: security; file '../../../../rbac/rbac_role_binding.yaml' is not in or below
'/Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/build/kustomize/rbac/rolebinding'

output=$(kustomize build build/kustomize/crd/protected/instances); echo "$output" > /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/deployments/helm/jenkins-operator/CR
D-protected/jenkins_v1alpha1_jenkinsinstance.yaml
Error: rawResources failed to read Resources: Load from path ../../../../../crd/jenkins_v1alpha1_jenkinsinstance.yaml failed: security; file '../../../../../crd/jenkins_v1alpha1_jenkins
instance.yaml' is not in or below '/Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/build/kustomize/crd/protected/instances'

output=$(kustomize build build/kustomize/crd/unprotected/instances); echo "$output" > /Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/deployments/helm/jenkins-operator/
CRD/jenkins_v1alpha1_jenkinsinstance.yaml
Error: rawResources failed to read Resources: Load from path ../../../../../crd/jenkins_v1alpha1_jenkinsinstance.yaml failed: security; file '../../../../../crd/jenkins_v1alpha1_jenkins
instance.yaml' is not in or below '/Users/alika/golang/src/github.com/samsung-cnct/jenkins-operator/build/kustomize/crd/unprotected/instances'
```

**Comment by maratoid** [comment]
I need to add build instructions. https://github.com/samsung-cnct/jenkins-operator/issues/21

**Comment by maratoid** [comment]
https://github.com/samsung-cnct/jenkins-operator/issues/22

**Comment by alika** [comment]
After switching to the correct golang project (`$(GOPATH/src/github.com/maratoid/jenkins-operator)`), I was able to get a successful image test and build (`make -f build/Makefile docker-build`).

Since the local darwin build issues will be addressed by #21 and #22, I think this PR is good enough to merge.

**Comment by alika** [comment]
confirmed the kustomize fix. other than making sure to update the build docs on what build-tools need to be installed (controller-gen, kustomize, and kubebuilder) in #21, this LGTM.

**Pull request merged**
